export {
    PERMIT_STATUS_LABELS,
    INSPECTION_STATUS_LABELS,
    INVOICE_STATUS_LABELS,
    JURISDICTION_TAG_LABELS,
    PERMIT_STATUSES,
    INSPECTION_STATUSES,
    INVOICE_STATUSES,
    getPermitStatusLabel,
    getInspectionStatusLabel,
    getInvoiceStatusLabel,
    isValidPermitStatus,
    isValidInspectionStatus,
    isValidInvoiceStatus,
    type JurisdictionTag,
} from "./labels";
